### ISSUE TITLE
Бот игнорирует сообщения со ссылкой на пост ВКонтакте, расположенный на странице пользователя

### ISSUE THREAD

**Issue by HeroBrine1st** [Flexlug/Skeletron#10]
В регексе можно заменить ``-(\d+)`` на ``(-?\d+)``
https://github.com/Flexlug/Skeletron/blob/1f3d7cad2f3432d69b28d6b0a93e002470bf71ec/Skeletron/Converters/VkRegex.cs#L17-L18
А затем убрать ``-`` отсюда
https://github.com/Flexlug/Skeletron/blob/1f3d7cad2f3432d69b28d6b0a93e002470bf71ec/Skeletron/Converters/VkRegex.cs#L28
https://github.com/Flexlug/Skeletron/blob/1f3d7cad2f3432d69b28d6b0a93e002470bf71ec/Skeletron/Converters/VkRegex.cs#L38

**Comment by Flexlug** [comment]
Недостаточно просто Regex поменять. Проблема в библиотеке, через которую идет взаимодействие с VK API.

https://github.com/Flexlug/Skeletron/blob/1f3d7cad2f3432d69b28d6b0a93e002470bf71ec/Skeletron/Services/VkPostToMessageService.cs#L63 

Метод не возвращает экземпляр `Post`. Парсить нечего.
А самое забавное, что на сайте с документацией VK API есть возможность потыкать методы. И если API напрямую скормить `post_id`, то всё работает корректно.

Тут 3 варианта:
- Искать другую библиотеку для взаимодействия с VK API;
- Искать ошибку в библиотеке и править её;
- Писать свою либу.

В любом случае эта проблема будет решена не моментально.

**Comment by Flexlug** [comment]
Похоже, что эту проблему удалось решить просто обновив библиотеку. 
Также сильно упростился процесс получения данных об авторе поста.

Сейчас запущен Skeletron из ветки [bot-ignores-posts-from-profile](https://github.com/Flexlug/Skeletron/tree/bot-ignores-posts-from-profile). Если в ближайшие пару дней всё будет стабильно, то пушим в мастер.
