### ISSUE TITLE
Опечатка в сообщении лога

### ISSUE THREAD

**Issue by Hlebushek2020** [Flexlug/Skeletron#13]
https://github.com/Flexlug/Skeletron/blob/bf4fed22ceed8483cdddc09fe2b385be79427d84/Skeletron/Services/VkPostToMessageService.cs#L82-L86

Опечатка в сообщении лога + я бы не стал в коде все же такие сообщения писать на русском

**Comment by Flexlug** [comment]
В боте очень много логов на русском языке. Переписывать все пока не вижу смысла.
